# Generated by Django 2.2.4 on 2019-08-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_votes_votes_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vote',
            field=models.IntegerField(default=1),
        ),
    ]
